on:
  push:
    branches-ignore: ['master']
  workflow_call:    

name: Push - Build, Unit Test

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - uses: actions/upload-artifact@v4
        with:
          name: kiryuu
          path: ./target/debug/kiryuu

  tracing:
    name: Check tracing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Check w/ tracing
        run: cargo check --features tracing
    
          