on: [push, pull_request]

name: Build & Test

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        continue-on-error: false
        with:
          command: test

  redis-test:
    name: Test with redis-test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis

        ports:
          - 6379:6379

        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      qbit-svc:
        image: ghcr.io/ckcr4lyf/qbit-svc

        ports:
          - 8888:8080

        volumes:
          - /qbit-svc/downloads:/downloads
          - /qbit-svc/watch:/watch

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create file, torrent. Add to qbit-svc
        run: |
          ifconfig
          sudo apt-get -y install tcpdump
          tcpdump --version
          IF_NAME="$(ifconfig | grep -B1 "172.18.0.1" | head -n1 | awk '{print $1}' | cut -d ':' -f1)"
          echo $IF_NAME
          sudo tcpdump -nnSX port 6969 -i $IF_NAME &>tcpdump_host.log &
          whoami
          sudo chmod -R 777 /qbit-svc
          ls -l /qbit-svc
          mkdir /tmp/imdl
          wget -O imdl.tar.gz https://github.com/casey/intermodal/releases/download/v0.1.12/imdl-v0.1.12-x86_64-unknown-linux-musl.tar.gz
          tar xvzf imdl.tar.gz -C /tmp/imdl
          echo "hello" > hello.txt
          sha256sum hello.txt
          /tmp/imdl/imdl torrent create -a http://172.17.0.1:6969/announce hello.txt
          cp hello.txt /qbit-svc/downloads/

      - name: Build kiryuu
        run: cargo build

      - name: Run kiryuu (in background)
        run: ./target/debug/kiryuu --redis-host 127.0.0.1:6379 &

      - name: Copy torrent to watch dir
        run: cp hello.txt.torrent /qbit-svc/watch/

      - name: Healthcheck
        run: |
          if [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://127.0.0.1:6969/healthz)" != "200" ]]
            then exit 1
            else exit 0
          fi

      - name: Docker qbit
        uses: ckcr4lyf/actions-kiryuu-qbit-test@v2
        with:
          torrent_name: hello.txt.torrent

      - name: Kill Kiryuu
        run: kill -9 `lsof -i:6969 -t`

      - name: tcpdump logs
        uses: actions/upload-artifact@v3
        with:
          name: tcpdump_logs
          path: |
            ./tcpdump.log
            ./tcpdump_host.log
