on:
  push:
    branches: ['master']

name: Master - Build, Unit Test, Integration test

jobs:
  build:
    uses: ./.github/workflows/build.yml

  integration-tests:
    uses: ./.github/workflows/integration-test.yml